version: '3'
services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./db:/data/db
  app:
    build: ./backend
    expose:
      - ${API_PORT}
    environment:
      API_PORT: ${API_PORT}
    user: "1000"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/app
    links:
      - mongo
    command: yarn start
