version: '3'
services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - dbdata:/data/db
  app:
    build: .
    expose:
      - ${PORT}
    environment:
      PORT: ${PORT}
    user: '1000'
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - mongo
    command: yarn dev

volumes:
  dbdata:
  node_modules:
